;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        handle-switch-frame
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-kill-line
        org-self-insert-command
        sgml-slash
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        ))
