;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        View-scroll-page-forward
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        coffee-dedent-line-backspace
        comment-dwim
        delete-horizontal-space
        electric-newline-and-maybe-indent
        eval-last-sexp
        evaluate-region-using-units
        handle-switch-frame
        indent-for-tab-command
        kill-region
        mouse-yank-primary
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-fill-paragraph
        org-kill-line
        org-self-insert-command
        org-yank
        picture-self-insert
        python-indent-shift-right
        sgml-slash
        sh-assignment
        smart-quotes-insert-single
        ))

(setq mc/cmds-to-run-once
      '(
        ag-current-word
        c-electric-slash
        ido-switch-buffer
        point-to-register
        ))
