;; Install third-party packages

(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("melpa" . "http://melpa.milkbox.net/packages/")
        ))
(package-initialize)
(package-refresh-contents)
(package-install 'ag)
(package-install 'blacken)
(package-install 'browse-kill-ring)
(package-install 'coffee-mode)
(package-install 'fzf)
(package-install 'git-timemachine)
(package-install 'go-mode)
(package-install 'json-mode)
(if (>= emacs-major-version 25)
    (progn
      (package-install 'flycheck)
      (package-install 'lsp-mode)
      (package-install 'lsp-ui)
      (package-install 'magit)
      (package-install 'projectile)
      ))
(package-install 'multiple-cursors)
(package-install 'org)
(package-install 'typescript-mode)
